export const banks = {
  Venezuela: [
    { code: '0001', name: 'Banco Central de Venezuela' },
    { code: '0102', name: 'Banco de Venezuela S.A.C.A. Banco Universal' },
    { code: '0104', name: 'Venezolano de Crédito, S.A. Banco Universal' },
    { code: '0105', name: 'Banco Mercantil, C.A. Banco Universal' },
    { code: '0108', name: 'Banco Provincial, S.A. Banco Universal' },
    { code: '0114', name: 'Bancaribe C.A. Banco Universal' },
    { code: '0115', name: 'Banco Exterior, C.A. Banco Universal' },
    { code: '0128', name: 'Banco Caroní, C.A. Banco Universal' },
    { code: '0134', name: 'Banesco Banco Universal S.A.C.A.' },
    { code: '0137', name: 'Banco Sofitasa, C.A. Banco Universal' },
    { code: '0138', name: 'Banco Plaza, C.A. Banco Universal' },
    { code: '0146', name: 'Bangente, C.A. Banco Universal' },
    { code: '0151', name: 'BFC Banco Fondo Común, C.A. Banco Universal' },
    { code: '0156', name: '100% Banco, C.A. Banco Universal' },
    { code: '0157', name: 'DelSur, C.A. Banco Universal' },
    { code: '0163', name: 'Banco del Tesoro, C.A. Banco Universal' },
    { code: '0166', name: 'Banco Agrícola de Venezuela, C.A. Banco Universal' },
    { code: '0168', name: 'Bancrecer, S.A. Banco Universal' },
    { code: '0169', name: 'Mi Banco, C.A. Banco Universal' },
    { code: '0171', name: 'Banco Activo, C.A. Banco Universal' },
    { code: '0172', name: 'Bancamiga, C.A. Banco Universal' },
    { code: '0173', name: 'Banco Internacional de Desarrollo, C.A. Banco Universal' },
    { code: '0174', name: 'Banplus Banco Universal, C.A.' },
    { code: '0175', name: 'Banco Bicentenario del Pueblo, Banco Universal C.A.' },
    { code: '0177', name: 'Banco de la Fuerza Armada Nacional Bolivariana, B.U.' },
    { code: '0191', name: 'Banco Nacional de Crédito, C.A. Banco Universal' },
  ],
  Colombia: [
    { code: '0001', name: 'Banco de la República' },
    { code: '0002', name: 'Bancolombia S.A.' },
    { code: '0003', name: 'Banco de Bogotá S.A.' },
    { code: '0006', name: 'Itaú Corpbanca Colombia S.A.' },
    { code: '0007', name: 'Banco Popular S.A.' },
    { code: '0009', name: 'Citibank Colombia' },
    { code: '0013', name: 'Banco GNB Sudameris S.A.' },
    { code: '0014', name: 'BBVA Colombia' },
    { code: '0023', name: 'Banco de Occidente S.A.' },
    { code: '0031', name: 'Banco Davivienda S.A.' },
    { code: '0040', name: 'Banco Agrario de Colombia S.A.' },
    { code: '0051', name: 'Banco Caja Social S.A.' },
    { code: '0052', name: 'Banco Falabella S.A.' },
    { code: '0058', name: 'Bancoomeva S.A.' },
    { code: '0059', name: 'Banco Pichincha S.A.' },
    { code: '0060', name: 'Banco W S.A.' },
    { code: '0061', name: 'Finandina S.A.' },
    { code: '0062', name: 'Scotiabank Colpatria S.A.' },
    { code: '0063', name: 'Banco Serfinanza S.A.' },
    { code: '0065', name: 'BTG Pactual S.A. Comisionista de Bolsa' },
    { code: '0066', name: 'Lulo Bank S.A.' },
    { code: '0067', name: 'RappiPay' },
    { code: '0068', name: 'Nequi' },
    { code: '0069', name: 'Daviplata' },
  ],
};
